output_sample_rate: 44100
num_channels: 2

desired_publishing_rate: 100.0
# num_frames_per_period: 32768
num_frames_per_period: 16384
# num_frames_per_period: 8192
# num_output_signals: 28
num_output_signals: 28

published_output_index_range: [4, 12]

# mel_filter_parameter_a: 700.0
# mel_filter_parameter_b: 2595.0
# mel_filter_parameter_a: 200.0
# mel_filter_parameter_b: 22595.0

mel_filter_parameter_a: 700.0
mel_filter_parameter_b: 2595.0

sound_card_id: 1
device_id: 0

apply_hamming_window: false
apply_dct: false

dct_output_scaling:
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
dct_output_offset:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
no_dct_output_scaling:
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
  - 5.9
no_dct_output_offset:
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53
  - -0.53


#dct_output_scaling:
#  - 100.0
#  - 100.0
#  - 40.0
#  - 50.0
#  - 25.0
#  - 25.0
#  - 25.0
#  - 20.0
#  - 16.0
#  - 10.0
#  - 12.0
#  - 12.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 6.0
#  - 10.0
#  - 20.0
#  - 6.0
#  - 10.0
#  - 10.0
#  - 10.0
#dct_output_offset:
#  - -0.9
#  - 0.2
#  - -0.1
#  - -0.7
#  - -2.0
#  - -2.5
#  - -2.0
#  - -2.3
#  - -2.2
#  - -2.5
#  - -1.4
#  - -0.0
#  - -0.0
#  - -0.0
#  - -0.0
#  - -0.0
#  - -0.0
#  - -0.0
#  - -0.5
#  - -1.0
#  - -1.2
#  - -1.0
#  - -0.8
#  - 0.0
#  - -0.8
#  - 0.0
#  - 0.0
#  - 0.5
#no_dct_output_scaling:
#  - 6.0
#  - 6.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 3.0
#  - 40.0
#  - 30.0
#  - 50.0
#  - 80.0
#no_dct_output_offset:
#  - -0.4
#  - -0.4
#  - -1.0
#  - -0.8
#  - -0.7
#  - -0.7
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.5
#  - -0.7
#  - -0.5
#  - -0.0
#  - -1.0

publish_visualization_markers: true
visualization_marker_topic: spectrum_markers_array
visualization_publishing_rate: 20.0
visualization_spectrum_length: 0.5
visualization_spectrum_max_amplitude: 1.0
visualization_spectrum_max_height: 0.25
spectrum_base_frame_pose:
  position:
    x: 0.25
    y: -0.1
    z: 1.8
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0