real_world: false
use_constraints: true
num_reps: 5
boxes:
  -
    name: box1
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 0.015000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box2
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 0.329000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box3
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 0.643000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box4
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 0.957000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box5
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 1.271000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box6
    frame: /base_footprint
    position: [ 0.800000, -0.100000, 1.585000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 1.200000, 0.030000 ]
  -
    name: box7
    frame: /base_footprint
    position: [ 0.800000, -0.685000, 0.800000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 0.030000, 1.600000 ]
  -
    name: box8
    frame: /base_footprint
    position: [ 0.800000, -0.295000, 0.800000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 0.030000, 1.600000 ]
  -
    name: box9
    frame: /base_footprint
    position: [ 0.800000, 0.095000, 0.800000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 0.030000, 1.600000 ]
  -
    name: box10
    frame: /base_footprint
    position: [ 0.800000, 0.485000, 0.800000 ]
    orientation: [ 0.0, 0.0, 0.0 ]
    dimensions: [ 0.400000, 0.030000, 1.600000 ]
poses_frame: /base_footprint
poses:
  - [ 0.600000, -0.490000, 0.172000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.100000, 0.172000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, 0.290000, 0.172000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.490000, 0.486000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.100000, 0.486000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, 0.290000, 0.486000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.490000, 0.800000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.100000, 0.800000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, 0.290000, 0.800000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.490000, 1.114000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.100000, 1.114000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, 0.290000, 1.114000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.490000, 1.428000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, -0.100000, 1.428000, 0.000000, 0.000000, 0.000000 ]
  - [ 0.600000, 0.290000, 1.428000, 0.000000, 0.000000, 0.000000 ]
